import {
    CONTROL_EXPRESSION_PEDAL_1,
    CONTROL_EXPRESSION_PEDAL_2, CONTROL_FOOTSWITCH_1, CONTROL_FOOTSWITCH_2, CONTROL_FOOTSWITCH_3, CONTROL_FOOTSWITCH_4,
    CONTROL_STOMPSWITCH_1, CONTROL_STOMPSWITCH_2, CONTROL_STOMPSWITCH_3, CONTROL_STOMPSWITCH_4, CONTROL_STOMPSWITCH_5,
    CONTROL_STOMPSWITCH_6, CONTROL_STOMPSWITCH_A, CONTROL_STOMPSWITCH_B, CONTROL_STOMPSWITCH_C, CONTROL_STOMPSWITCH_D,
    MSG_TYPES_EXP_PEDAL,
    MSG_TYPES_FOOTWITCH, MSG_TYPES_STOMPSWITCH
} from "./constants";

export function getAvailableMessageTypes(controlId) {
    switch (parseInt(controlId)) {
        case CONTROL_STOMPSWITCH_1:
        case CONTROL_STOMPSWITCH_2:
        case CONTROL_STOMPSWITCH_3:
        case CONTROL_STOMPSWITCH_4:
        case CONTROL_STOMPSWITCH_5:
        case CONTROL_STOMPSWITCH_6:
        case CONTROL_STOMPSWITCH_A:
        case CONTROL_STOMPSWITCH_B:
        case CONTROL_STOMPSWITCH_C:
        case CONTROL_STOMPSWITCH_D:
            return MSG_TYPES_STOMPSWITCH;
        case CONTROL_FOOTSWITCH_1:
        case CONTROL_FOOTSWITCH_2:
        case CONTROL_FOOTSWITCH_3:
        case CONTROL_FOOTSWITCH_4:
            return MSG_TYPES_FOOTWITCH;
        case CONTROL_EXPRESSION_PEDAL_1:
        case CONTROL_EXPRESSION_PEDAL_2:
            return MSG_TYPES_EXP_PEDAL;
        default:
            return [];
    }
}
